### ISSUE TITLE
No key assertion triggered

### ISSUE THREAD

**Issue by vebis** [afett/jsoncc#1]
[This input](https://raw.githubusercontent.com/nst/JSONTestSuite/master/test_parsing/y_object_empty_key.json) will trigger the assertion at https://github.com/afett/jsoncc/blob/877f285da4d7ce3f595a256b98915042842904bb/src/member.cc#L34
and forces a crash. It should throw an exception.

**Comment by afett** [comment]
Well, I don't really like exceptions. You are right, that this could be due to invalid input, in which an exception would be justified. But it could also be a programming error in which case the assert() is fine.

Also rfc8259 does not specify that the key or "name" must me non empty, so maybe this is no error at all and the application should check if this is not wanted.

**Comment by afett** [comment]
Thank you for reporting this.  I still think the assert is justified there as it's clearly a programming error. This should be fixed by the user code as I've done in the Parser class.
